### ISSUE TITLE
Deploy and configure Netlify CI/CD

### ISSUE THREAD

**Issue by arslanastral** [chingu-voyages/v41-bears-team-32#36]
**__Task Description__**
Deploy [v41-bears-team-32](https://github.com/chingu-voyages/v41-bears-team-32) using Netlify CI/CD.

**__Major User Stories/tasks__**
- [x] Make sure #34 is completed
- [x] Configure Netlify with repo
- [x] Add Netlify's Next.js plugin

**__Resources__**
[Netlify CI/CD](https://www.netlify.com/products/build/)
